# Generated by Django 5.1.1 on 2024-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerID', models.IntegerField()),
                ('survived', models.BooleanField()),
                ('pclass', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField(null=True)),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('ticket', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
                ('cabin', models.CharField(max_length=20, null=True)),
                ('embarked', models.CharField(max_length=1)),
            ],
        ),
    ]
