# Generated by Django 5.1.1 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titanic',
            old_name='cabin',
            new_name='Cabin',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='embarked',
            new_name='Embarked',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='fare',
            new_name='Fare',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='parch',
            new_name='Parch',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='passengerID',
            new_name='PassengerId',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='pclass',
            new_name='Pclass',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='sex',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='sibsp',
            new_name='SibSp',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='survived',
            new_name='Survived',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='ticket',
            new_name='Ticket',
        ),
        migrations.RemoveField(
            model_name='titanic',
            name='age',
        ),
        migrations.AddField(
            model_name='titanic',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
